{% set name = "wcmatch" %}
{% set version = "10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wcmatch-{{ version }}.tar.gz
  sha256: e72f0de09bba6a04e0de70937b0cf06e55f36f37b3deb422dfaf854b867b840a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=0.21.1
    - pip
  run:
    - python >={{ python_min }}
    - bracex >=2.1.1

test:
  imports:
    - wcmatch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/facelessuser/wcmatch
  summary: Wildcard/glob file name matcher.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asford
    - ocefpaf
