{% set name = "wcmatch" %}
{% set version = "7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wcmatch-{{ version }}.tar.gz
  sha256: d65b8fe04887130e487b93184ec01ff2b3b226e03a98855b8319f894e4c8adc6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - backrefs >=4.1
    - bracex >=2.0
    - python >=3.5

test:
  imports:
    - wcmatch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facelessuser/wcmatch
  summary: Wildcard/glob file name matcher.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asford
