{% set name = "wcmatch" %}
{% set version = "10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wcmatch-{{ version }}.tar.gz
  sha256: f11f94208c8c8484a16f4f48638a85d771d9513f4ab3f37595978801cb9465af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=0.21.1
    - pip
  run:
    - python >={{ python_min }}
    - bracex >=2.1.1

test:
  imports:
    - wcmatch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/facelessuser/wcmatch
  summary: Wildcard/glob file name matcher.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asford
    - ocefpaf
