schema_version: 1

context:
  version: "10.2.1"

package:
  name: wcmatch
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/w/wcmatch/wcmatch-${{ version }}.tar.gz
  sha256: ecac70a5c70e62ba854b78318d3a1408e8651f8f1c96e5837743b71aa6a4fb92

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=0.21.1
    - pip
  run:
    - python >=${{ python_min }}
    - bracex >=3.0
tests:
  - python:
      imports:
        - wcmatch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: Wildcard/glob file name matcher.
  license: MIT
  license_file: LICENSE.md
  homepage: https://github.com/facelessuser/wcmatch

extra:
  recipe-maintainers:
    - asford
    - ocefpaf
